[[liver]]
# uid
uid = 59275
# 房间号
roomid = 851181
# 备注，可能只是debug用
remark = "梦魇Tsuki"
# 分组
group = { tag = "tsuki" }
# 应援色
color = "#9c7ace"

#-------------------------------------------------- VRP
[[liver]]
uid = 421267475
roomid = 21403601
remark = "艾因"
group = { tag = "project", gen = 1 }

[[liver]]
uid = 420249427
roomid = 21403609
remark = "琉绮"
color = "#A00000"
group = { tag = "project", gen = 1 }


[[liver]]
uid = 434334701
roomid = 21452505
remark = "七海"
color = "#418BDE"
group = { tag = "project", gen = 2 }

[[liver]]
uid = 434401868
roomid = 21457197
remark = "中单光一"
color = "#f0f0ff"
group = { tag = "project", gen = 2 }

[[liver]]
uid = 455916618
roomid = 21571739
remark = "无理"
group = { tag = "project", gen = 3 }

[[liver]]
uid = 455965041
roomid = 21669084
remark = "羽音"
group = { tag = "project", gen = 3 }

[[liver]]
uid = 472821519
roomid = 21615277
remark = "喵月"
group = { tag = "project", gen = 4 }

[[liver]]
uid = 472845978
roomid = 21613353
remark = "有加"
group = { tag = "project", gen = 4 }

[[liver]]
uid = 472877684
roomid = 21613356
remark = "惑姬"
group = { tag = "project", gen = 4 }

[[liver]]
uid = 477317922
roomid = 21672023
remark = "弥希"
group = { tag = "project", gen = 5 }

[[liver]]
uid = 477342747
roomid = 21672022
remark = "星弥"
group = { tag = "project", gen = 5 }

[[liver]]
uid = 477306079
roomid = 21672024
remark = "真绯瑠"
group = { tag = "project", gen = 5 }

[[liver]]
uid = 480680646
roomid = 21696950
remark = "阿萨"
group = { tag = "project", gen = 6 }
color = "#B8E994"

[[liver]]
uid = 480675481
roomid = 21696929
remark = "八木迪之"
group = { tag = "project", gen = 6 }
color = "#704214"

[[liver]]
uid = 480745939
roomid = 21696953
remark = "罗伊"
group = { tag = "project", gen = 6 }
color = "#FFEC89"

[[liver]]
uid = 474369808
roomid = 21696957
remark = "度人"
group = { tag = "project", gen = 6 }


[[liver]]
uid = 56748733
roomid = 21756924
remark = "雪绘"
group = { tag = "project", gen = 7 }

[[liver]]
uid = 490331391
roomid = 21763344
remark = "沙夜"
group = { tag = "project", gen = 7 }

[[liver]]
uid = 319810877
roomid = 21763337
remark = "星也"
group = { tag = "project", gen = 7 }

[[liver]]
uid = 370687588
roomid = 22111428
remark = "花留"
group = { tag = "project", gen = 8 }


[[liver]]
uid = 370687372
roomid = 22111414
remark = "紫纪"
group = { tag = "project", gen = 8 }

[[liver]]
uid = 370689210
roomid = 22111450
remark = "萨麦尔"
group = { tag = "project", gen = 8 }

[[liver]]
uid = 628292881
roomid = 22389314
remark = "卡欧斯"
group = { tag = "project", gen = 9 }
color = "#BF0000"

[[liver]]
uid = 558070436
roomid = 22389323
remark = "清良"
group = { tag = "project", gen = 9 }

[[liver]]
uid = 558070433
roomid = 22389323
remark = "千春"
group = { tag = "project", gen = 9 }
color = "#800000"

[[liver]]
uid = 666726799
roomid = 22470216
remark = "悠亚"
group = { tag = "project", gen = 10 }

[[liver]]
uid = 666726800
roomid = 22470210
group = { tag = "project", gen = 10 }
remark = "星宸"
color = "#3755BD"

[[liver]]
uid = 666726801
roomid = 22470208
group = { tag = "project", gen = 10 }
remark = "勺"
color = "#707070"

[[liver]]
uid = 666726802
roomid = 22470204
group = { tag = "project", gen = 10 }
remark = "瑞芙"

[[liver]]
uid = 690608706
roomid = 22605469
group = { tag = "project", gen = 11 }
remark = "田野柴"

[[liver]]
uid = 690608691
roomid = 22605469
group = { tag = "project", gen = 11 }
remark = "千幽"
color = "#CC225F"

[[liver]]
uid = 690608686
roomid = 22605463
group = { tag = "project", gen = 11 }
remark = "茉里"
color = "#C70039"

[[liver]]
uid = 690608694
roomid = 22605466
group = { tag = "project", gen = 11 }
remark = "伊深"
color = "#CC777C"

[[liver]]
uid = 690608702
roomid = 22778627
group = { tag = "project", gen = 12 }
remark = "九十九"
color = "#C6B6EC"


[[liver]]
uid = 690608693
roomid = 22778610
group = { tag = "project", gen = 12 }
remark = "勾檀"
color = "#D6E568"

[[liver]]
uid = 690608687
roomid = 22778596
group = { tag = "project", gen = 12 }
remark = "蕾米"
color = "#77cfd4"

[[liver]]
uid = 690608701
roomid = 22778617
group = { tag = "project", gen = 12 }
remark = "犬童"

[[liver]]
uid = 690608704
roomid = 23017349
group = { tag = "project", gen = 13 }
remark = "桃星"

[[liver]]
uid = 690608688
roomid = 23017343
group = { tag = "project", gen = 13 }
remark = "吉吉"
color = "#FBA33E"

[[liver]]
uid = 690608696
roomid = 23017346
group = { tag = "project", gen = 13 }
remark = "绮楼"

[[liver]]
uid = 690608690
roomid = 23260932
group = { tag = "project", gen = 14 }
remark = "恋诗夜"
color = "#EE548E"

[[liver]]
uid = 690608698
roomid = 23260993
group = { tag = "project", gen = 14 }
remark = "瑞娅"
color = "#776ef2"

[[liver]]
uid = 690608689
roomid = 23260856
group = { tag = "project", gen = 14 }
remark = "夜宫"

[[liver]]
uid = 690608695
roomid = 23260979
group = { tag = "project", gen = 14 }
remark = "库伽"

[[liver]]
uid = 690608692
roomid = 23260965
group = { tag = "project", gen = 14 }
remark = "未羽"

[[liver]]
uid = 690608709
roomid = 23550749
group = { tag = "project", gen = 15 }
remark = "尤格"
color = "#6671BC"

[[liver]]
uid = 690608710
roomid = 23550773
group = { tag = "project", gen = 15 }
remark = "暴食"
color = "#6f1313"

[[liver]]
uid = 690608711
roomid = 23550784
group = { tag = "project", gen = 15 }
remark = "克克"
color = "#ff0329"

[[liver]]
uid = 690608712
roomid = 23550793
group = { tag = "project", gen = 15 }
remark = "友夏"
color = "#a72424"

[[liver]]
uid = 1405589619
roomid = 23805059
group = { tag = "project", gen = 16 }
remark = "希维"
color = "#91CAD1"

[[liver]]
uid = 1484169431
roomid = 23805029
group = { tag = "project", gen = 16 }
remark = "雾深"
color = "#1E377F"

[[liver]]
uid = 690608714
roomid = 23805078
group = { tag = "project", gen = 16 }
remark = "狩砂"
color = "#B4BBC4"

[[liver]]
uid = 1155425566
roomid = 23805066
group = { tag = "project", gen = 16 }
remark = "希侑"
color = "#FF91AE"

[[liver]]
uid = 1116072703
roomid = 25788858
group = { tag = "project", gen = 17 }
remark = "莱恩"
color = "#FFDB79"

[[liver]]
uid = 1739085910
roomid = 25788830
group = { tag = "project", gen = 17 }
remark = "江乱"
color = "#AE55E6"

[[liver]]
uid = 1954091502
roomid = 25788785
group = { tag = "project", gen = 17 }
remark = "岁己"
color = "#87EAFF"


[[liver]]
uid = 1542516095
roomid = 26966452
group = { tag = "project", gen = 18 }
remark = "伊舞"


[[liver]]
uid = 1827139579
roomid = 25762103
group = { tag = "project", gen = 18 }
remark = "欧珀"


[[liver]]
uid = 1609526545
roomid = 26966466
group = { tag = "project", gen = 18 }
remark = "栞栞"

#-------------------------------------------------- VRP


#-------------------------------------------------- VR-LINK

[[liver]]
uid = 7706705
roomid = 510
remark = "阿梓"
color = "#b4b8fd"
group = { tag = "link" }

[[liver]]
uid = 14387072
roomid = 605
remark = "小可"
group = { tag = "link" }

[[liver]]
uid = 1750561
roomid = 8721033
remark = "蜜球兔"
group = { tag = "link" }

[[liver]]
uid = 392505232
roomid = 21224291
remark = "安堂いなり"
group = { tag = "link" }

[[liver]]
uid = 98181
roomid = 4418655
remark = "菫妃奈"
group = { tag = "link" }

[[liver]]
uid = 471308347
roomid = 21664698
remark = "寿寿歌"
group = { tag = "link" }

[[liver]]
uid = 322210278
roomid = 21736138
remark = "魔魔マラ"
group = { tag = "link" }

[[liver]]
uid = 741520
roomid = 33942
remark = "茶冷"
group = { tag = "link" }

[[liver]]
uid = 666726803
roomid = 22470189
remark = "伊莎贝拉"
group = { tag = "link" }

[[liver]]
uid = 6853766
roomid = 3032130
remark = "舒三妈"
group = { tag = "link" }

[[liver]]
uid = 7706705
roomid = 529249
remark = "诺莺"
group = { tag = "link" }

[[liver]]
uid = 176836079
roomid = 6068126
remark = "糯依"
group = { tag = "link" }

[[liver]]
uid = 61639371
roomid = 21484828
remark = "轴伊"
group = { tag = "link" }

[[liver]]
uid = 12485637
roomid = 784734
remark = "宫园凛"
group = { tag = "link" }
#-------------------------------------------------- VR-LINK
